---
name: Build the plugin
on: [ push ]
jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        spigot:
          - 1.20.4-R0.1-SNAPSHOT
          - 1.20.2-R0.1-SNAPSHOT
          - 1.20.1-R0.1-SNAPSHOT
          - 1.19.4-R0.1-SNAPSHOT
          - 1.18.2-R0.1-SNAPSHOT
        cloudnet:
          - 3.4.5-RELEASE
          - 3.3.0-RELEASE
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven repository
        id: cache-mvn
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: Package plugin
        run: mvn package -Dspigot.version=${{ matrix.spigot }} -Dcloudnet.version=${{ matrix.cloudnet }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache maven repository
        id: cache-mvn
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5

      - name: Package plugin
        run: mvn package

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CloudNet-PlaceholderExpansion
          path: target/*.jar